version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/timbi
      SPRING_DATASOURCE_USERNAME: saldi
      SPRING_DATASOURCE_PASSWORD: saldi
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: saldi
      MYSQL_DATABASE: saldi
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
